name: yaib
channels:
  - pytorch
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - black=22.10.0
  - coverage=6.5.0
  - flake8=5.0.4
  - gin-config=0.5.0
  - ignite=0.4.10
  - pytorch=1.13.1
  - lightgbm=3.3.3
  - numpy=1.23.4
  - pandas=1.5.1
  - pyarrow=9.0.0
  - pytest=7.2.0
  - scikit-learn=1.1.3
  - tensorboard=2.11.0
  - tqdm=4.64.1
  - pytorch-lightning=1.9.2
  - wandb=0.13.10
  - pip=22.3.1
  - scikit-optimize=0.9.0
  - einops=0.4.1
  - pip:
      - git+https://github.com/rvandewater/recipys.git
      - hyperimpute==0.1.16
      - pypots==0.0.9
      - rpy2==3.5.6

